"use strict";

/*
 * Reports for internal readers (team manager, project managers), printed with
 * the browser's own Print / Save as PDF. Nothing leaves the machine.
 *
 *   weekly   Weekly status update        (team manager)
 *   project  Project status              (project manager)
 *   monthly  Monthly capacity & delivery (team manager)
 *   history  Task / deliverable history  (on request)
 *
 * The unit of work is a deliverable (its cards rolled up) or, for cards without
 * a deliverable, the card itself. "Internal" is the project for non-project time.
 */

const RP_INTERNAL = "internal";

const Reports = {
  sheet: document.getElementById("rp-sheet"),
  typeSel: document.getElementById("rp-type"),
  controls: document.getElementById("rp-controls"),
  view: { type: "weekly", week: startOfWeek(todayISO()), month: todayISO().slice(0, 7), project: "", item: "", notes: false, internal: true },
  VIEW_KEY: "work-tracker-report-view",
  csv: null,

  init() {
    try { Object.assign(this.view, JSON.parse(localStorage.getItem(this.VIEW_KEY)) || {}); } catch (e) { /* ignore */ }
    this.view.week = startOfWeek(this.view.week || todayISO());
    this.typeSel.value = this.view.type;
    this.typeSel.addEventListener("change", () => { this.view.type = this.typeSel.value; this.save(); this.render(); });
    document.getElementById("rp-print").addEventListener("click", () => window.print());
    document.getElementById("rp-csv").addEventListener("click", () => {
      if (!this.csv) return;
      downloadFile(this.csv.name, this.csv.rows.map((r) => r.map(csvCell).join(",")).join("\r\n"), "text/csv");
    });
  },

  save() { try { localStorage.setItem(this.VIEW_KEY, JSON.stringify(this.view)); } catch (e) { /* ignore */ } },

  settings() {
    const s = Store.state.settings;
    return {
      capacity: Number(s.weeklyCapacity) > 0 ? Number(s.weeklyCapacity) : 40,
      author: s.reportAuthor || "",
      budgets: s.projectBudgets || {},
      highlights: s.weeklyHighlights || {},
    };
  },

  render() {
    this.renderControls();
    this.sheet.innerHTML = "";
    this.csv = null;
    const fn = { weekly: this.weekly, project: this.project, monthly: this.monthly, history: this.history }[this.view.type] || this.weekly;
    this.sheet.append(...[].concat(fn.call(this)));
    this.sheet.append(h("footer", { class: "rp-foot" }, "Generated by work.tracker on " + fmtDate(todayISO())));
  },

  /* ---------- toolbar controls per report ---------- */

  renderControls() {
    const c = this.controls;
    c.innerHTML = "";
    const v = this.view, st = this.settings();
    const commitSetting = (fn) => Store.commit((s) => fn(s.settings));
    if (v.type === "weekly") {
      const wk = h("input", { type: "date", value: v.week, "aria-label": "Week" });
      wk.addEventListener("change", () => { if (wk.value) { v.week = startOfWeek(wk.value); this.save(); this.render(); } });
      c.append(
        h("button", { class: "btn btn-ghost btn-small", "aria-label": "Previous week", onclick: () => { v.week = addDays(v.week, -7); this.save(); this.render(); } }, "‹"),
        wk,
        h("button", { class: "btn btn-ghost btn-small", "aria-label": "Next week", onclick: () => { v.week = addDays(v.week, 7); this.save(); this.render(); } }, "›"),
        h("button", { class: "btn btn-ghost btn-small", onclick: () => { v.week = startOfWeek(todayISO()); this.save(); this.render(); } }, "This week"),
        this.check("Session notes appendix", "notes"));
    } else if (v.type === "monthly") {
      const m = h("input", { type: "month", value: v.month, "aria-label": "Month" });
      m.addEventListener("change", () => { if (m.value) { v.month = m.value; this.save(); this.render(); } });
      c.append(m);
    } else if (v.type === "project") {
      const projects = Store.projects().filter((p) => p.key !== RP_INTERNAL);
      if (!projects.some((p) => p.key === v.project)) v.project = projects.length ? projects[0].key : "";
      const sel = h("select", { "aria-label": "Project" }, projects.map((p) => h("option", { value: p.key, selected: p.key === v.project }, p.label)));
      sel.addEventListener("change", () => { v.project = sel.value; this.save(); this.render(); });
      const budget = h("input", { type: "number", min: "0", step: "1", value: st.budgets[v.project] != null ? st.budgets[v.project] : "", placeholder: "sum of estimates", class: "rp-num", "aria-label": "Project budget (h)" });
      budget.addEventListener("change", () => commitSetting((s) => {
        s.projectBudgets = Object.assign({}, s.projectBudgets);
        if (budget.value === "") delete s.projectBudgets[v.project];
        else s.projectBudgets[v.project] = Number(budget.value);
      }));
      c.append(sel, h("label", { class: "small rp-inline" }, "Budget (h) ", budget));
    } else if (v.type === "history") {
      const sel = h("select", { "aria-label": "Task or deliverable" });
      const groups = new Map();
      for (const d of Store.deliverableList()) (groups.get(d.project) || groups.set(d.project, []).get(d.project)).push(["d:" + d.id, "◆ " + d.name]);
      for (const r of Store.resourceList(true)) if (!r.deliverableId || !Store.deliverable(r.deliverableId)) {
        const k = Store.projectKey(r);
        (groups.get(k) || groups.set(k, []).get(k)).push(["c:" + r.id, r.title + (r.archived ? " (archived)" : "")]);
      }
      const keys = [...groups.keys()].sort((a, b) => Store.projectLabel(a).localeCompare(Store.projectLabel(b)));
      for (const k of keys) sel.append(h("optgroup", { label: Store.projectLabel(k) }, groups.get(k).map(([val, label]) => h("option", { value: val }, label))));
      const all = [...sel.querySelectorAll("option")].map((o) => o.value);
      if (!all.includes(v.item)) v.item = all[0] || "";
      sel.value = v.item;
      sel.addEventListener("change", () => { v.item = sel.value; this.save(); this.render(); });
      c.append(sel);
    }
    if (v.type === "weekly" || v.type === "monthly") {
      const cap = h("input", { type: "number", min: "1", step: "0.5", value: st.capacity, class: "rp-num", "aria-label": "Weekly capacity (h)" });
      cap.addEventListener("change", () => commitSetting((s) => { s.weeklyCapacity = Number(cap.value) || 40; }));
      c.append(h("label", { class: "small rp-inline" }, "Capacity (h/week) ", cap));
    }
    const name = h("input", { value: st.author, placeholder: "Your name", class: "rp-name", "aria-label": "Your name" });
    name.addEventListener("change", () => commitSetting((s) => { s.reportAuthor = name.value.trim(); }));
    c.append(name);
  },

  check(label, key) {
    const box = h("input", { type: "checkbox", checked: !!this.view[key] });
    box.addEventListener("change", () => { this.view[key] = box.checked; this.save(); this.render(); });
    return h("label", { class: "small rp-inline" }, box, " " + label);
  },

  /* ---------- shared data helpers ---------- */

  isInternal(key) { return key === RP_INTERNAL; },

  // Deliverables (cards rolled up) + cards without a deliverable.
  units() {
    const out = [];
    const seen = new Set();
    for (const r of Store.resourceList(true)) {
      const d = Store.deliverable(r.deliverableId);
      if (d) {
        if (seen.has(d.id)) continue;
        seen.add(d.id);
        out.push(this.dlvUnit(d));
      } else out.push(this.cardUnit(r));
    }
    return out;
  },

  cardUnit(r) {
    const col = Store.column(r.status);
    return {
      key: "c:" + r.id, kind: "card", id: r.id, title: r.title, project: Store.projectKey(r), categoryId: r.categoryId,
      cards: [r], logs: Store.logsFor(r.id), estHours: r.estHours ? Number(r.estHours) : null,
      dueDate: r.plannedEnd || "", startDate: r.plannedStart || "", done: Store.isDone(r), doneAt: r.doneAt || "",
      statusNote: r.statusNote || "", statusUpdatedAt: r.statusUpdatedAt || "", archived: !!r.archived,
      column: col, onHold: !Store.isDone(r) && col.kind === "hold", sessions: Store.sessionsFor(r.id), notes: r.notes || "",
    };
  },

  dlvUnit(d) {
    const sm = Store.deliverableSummary(d);
    const cols = Store.columns();
    const doing = sm.cards.find((r) => Store.kindOf(r.status) === "doing");
    const column = sm.issued ? (cols.find((c) => c.kind === "done") || cols[cols.length - 1])
      : sm.onHold.length ? Store.column(sm.onHold[0].status)
        : doing ? Store.column(doing.status) : Store.column((sm.cards[0] || {}).status);
    return {
      key: "d:" + d.id, kind: "deliverable", id: d.id, title: d.name, project: d.project, categoryId: (sm.cards[0] || {}).categoryId || null,
      cards: sm.cards, logs: sm.logs, estHours: sm.estHours, dueDate: sm.dueDate, startDate: sm.startDate,
      done: sm.issued, doneAt: sm.issuedAt, statusNote: sm.statusNote, statusUpdatedAt: sm.statusUpdatedAt,
      archived: sm.archived, column, onHold: !sm.issued && sm.onHold.length > 0, sessions: sm.sessions, notes: "",
    };
  },

  minutesIn(logs, from, to) { return logs.reduce((s, l) => s + (l.date >= from && l.date <= to ? l.minutes : 0), 0); },
  actual(u) { return u.logs.reduce((s, l) => s + l.minutes, 0); },

  // Date a card entered its current waiting (On hold) column, from the hidden move records.
  holdSince(r) {
    const label = Store.column(r.status).label;
    const moves = (r.history || []).filter((e) => e.kind === "move" && e.to === label);
    return moves.length ? moves[moves.length - 1].date : (r.statusUpdatedAt || "");
  },
  unitHoldSince(u) {
    const dates = u.cards.filter((r) => !Store.isDone(r) && Store.kindOf(r.status) === "hold").map((r) => this.holdSince(r)).filter(Boolean).sort();
    return dates[0] || "";
  },

  // Days a card spent in On-hold columns between from and to, from its move records.
  holdDaysIn(r, from, to) {
    const holdLabels = new Set(Store.columns().filter((c) => c.kind === "hold").map((c) => c.label));
    const moves = (r.history || []).filter((e) => e.kind === "move").sort((a, b) => (a.at || a.date).localeCompare(b.at || b.date));
    let days = 0, since = null;
    const close = (end) => {
      if (!since) return;
      // Days from entering the waiting column up to (not including) the day it left, within the period.
      const lim = addDays(to, 1);
      const a = since > from ? since : from, b = end < lim ? end : lim;
      if (b >= a) days += daysBetween(a, b);
      since = null;
    };
    for (const m of moves) {
      if (holdLabels.has(m.to)) { if (!since) since = m.date; } else close(m.date);
    }
    if (since && !Store.isDone(r) && Store.kindOf(r.status) === "hold") close(addDays(to, 1) < todayISO() ? addDays(to, 1) : todayISO());
    return days;
  },

  forecast(u) {
    const a = this.actual(u) / 60;
    if (u.done || !u.estHours) return a;
    return Math.max(u.estHours, a);
  },

  // G / A / R for a unit as of a date (proposal shown in the report footer).
  rag(u, asOf) {
    if (u.done) return "G";
    if (u.dueDate && u.dueDate < asOf) return "R";
    const since = u.onHold ? this.unitHoldSince(u) : "";
    if (since && daysBetween(since, asOf) > 5) return "A";
    if (u.estHours && this.actual(u) / 60 > u.estHours) return "A";
    return "G";
  },

  projectRag(key, asOf) {
    const units = this.units().filter((u) => u.project === key);
    const rags = units.map((u) => this.rag(u, asOf));
    const schedule = rags.includes("R") ? "R" : rags.includes("A") ? "A" : "G";
    const b = this.budgetFor(key, units);
    const fc = units.reduce((s, u) => s + this.forecast(u), 0);
    const budget = !b.hours ? "G" : fc > b.hours * 1.1 ? "R" : fc > b.hours + 0.01 ? "A" : "G";
    const worst = [schedule, budget].includes("R") ? "R" : [schedule, budget].includes("A") ? "A" : "G";
    return { overall: worst, schedule, budget, forecast: fc, units, rags };
  },

  budgetFor(key, units) {
    const set = this.settings().budgets[key];
    if (set != null && set !== "") return { hours: Number(set), source: "set" };
    const sum = units.reduce((s, u) => s + (u.estHours || 0), 0);
    return { hours: sum || null, source: "estimates" };
  },

  workdays(from, to) {
    let n = 0;
    for (let d = from; d <= to; d = addDays(d, 1)) { const g = fromISO(d).getDay(); if (g !== 0 && g !== 6) n++; }
    return n;
  },

  /* ---------- small view builders ---------- */

  header(title, sub, meta) {
    return h("header", { class: "rp-head" },
      h("div", {}, h("div", { class: "rp-brand" }, "{ } work.tracker"), h("h1", {}, title), h("div", { class: "rp-sub" }, sub)),
      h("div", { class: "rp-meta" }, meta.filter(([, v]) => v).map(([k, v]) => [h("span", {}, k), h("b", {}, v)])));
  },
  kpis(items) {
    return h("div", { class: "rp-kpis" }, items.map(([label, value, sub, cls]) =>
      h("div", { class: "rp-kpi " + (cls || "") }, h("div", { class: "rp-kl" }, label), h("div", { class: "rp-kv" }, value), h("div", { class: "rp-ks" }, sub || ""))));
  },
  h2(text, note) { return h("h2", {}, text, note ? h("span", { class: "rp-note" }, " " + note) : null); },
  chip(color) { return h("span", { class: "rp-chip", style: { background: color } }); },
  ragChip(level, text) {
    const word = { G: "Green", A: "Amber", R: "Red" }[level];
    return h("span", { class: "rp-rag rag-" + level }, h("i"), text || word);
  },
  dot(level) { return h("span", { class: "rp-dot rag-" + level }); },
  bar(pct, over) { return h("span", { class: "rp-bar" + (over ? " over" : "") }, h("span", { style: { width: Math.min(100, pct) + "%" } })); },
  table(head, rows, foot, cls) {
    return h("table", { class: "rp-table " + (cls || "") },
      h("thead", {}, h("tr", {}, head.map((x) => (typeof x === "string" ? h("th", {}, x) : x)))),
      h("tbody", {}, rows),
      foot ? h("tfoot", {}, foot) : null);
  },
  num(v, cls) { return h("td", { class: "num " + (cls || "") }, v); },
  colPill(u) {
    if (u.done) return h("span", { class: "rp-pill done" }, "Issued" + (u.doneAt ? " " + fmtShortDate(u.doneAt) : ""));
    const kind = u.column ? u.column.kind : "todo";
    return h("span", { class: "rp-pill " + kind }, u.column ? u.column.label : "—");
  },
  projColor(key) { return key === RP_INTERNAL ? "#9aa1ad" : Store.projectColor(key); },
  projLabel(key) { return Store.projectLabel(key); },

  // Stacked bars (one per period) with an optional capacity tick. series: [{ label, color, values[] }]
  barsSvg(cats, series, capacity, width, height) {
    const totals = cats.map((_, i) => series.reduce((s, x) => s + (x.values[i] || 0), 0));
    const mx = Math.max(1, ...totals, ...(capacity || [])) * 1.18;
    const pl = 34, pb = 20, pt = 12, ch = height - pb - pt, cw = (width - pl) / cats.length, bw = cw * 0.55;
    const y = (v) => pt + ch - (v / mx) * ch;
    const step = mx > 120 ? 40 : mx > 60 ? 20 : mx > 25 ? 10 : 5;
    let out = `<svg viewBox="0 0 ${width} ${height}" width="100%" role="img">`;
    for (let v = 0; v <= mx; v += step) out += `<line x1="${pl}" x2="${width}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}" class="g"/><text x="${pl - 5}" y="${(y(v) + 3).toFixed(1)}" class="ax" text-anchor="end">${v}</text>`;
    cats.forEach((c, i) => {
      const cx = pl + i * cw + (cw - bw) / 2;
      let base = 0;
      for (const sr of series) {
        const v = sr.values[i] || 0;
        if (v > 0) out += `<rect x="${cx.toFixed(1)}" y="${y(base + v).toFixed(1)}" width="${bw.toFixed(1)}" height="${(y(base) - y(base + v)).toFixed(1)}" style="fill:${sr.color}"/>`;
        base += v;
      }
      let label = fmtH(base * 60);
      let top = y(base);
      if (capacity) {
        const cy = y(capacity[i]);
        out += `<line x1="${(cx - 6).toFixed(1)}" x2="${(cx + bw + 6).toFixed(1)}" y1="${cy.toFixed(1)}" y2="${cy.toFixed(1)}" class="cap"/>`;
        if (capacity[i]) label += " · " + Math.round((base / capacity[i]) * 100) + "%";
        top = Math.min(top, cy);
      }
      out += `<text x="${(cx + bw / 2).toFixed(1)}" y="${(top - 4).toFixed(1)}" class="bt" text-anchor="middle">${esc(label)}</text>`;
      out += `<text x="${(cx + bw / 2).toFixed(1)}" y="${height - 5}" class="ax" text-anchor="middle">${esc(c)}</text>`;
    });
    return h("div", { class: "rp-chart", html: out + "</svg>" });
  },

  hbarsSvg(items, unit) {
    if (!items.length) return h("p", { class: "rp-muted" }, "Nothing to show.");
    const width = 330, rh = 19, lw = 128, mx = Math.max(...items.map((x) => x.value), 0.0001);
    let out = `<svg viewBox="0 0 ${width} ${items.length * rh + 4}" width="100%" role="img">`;
    items.forEach((it, i) => {
      const w = ((width - lw - 46) * it.value) / mx, yy = i * rh;
      const name = it.label.length > 22 ? it.label.slice(0, 21) + "…" : it.label;
      out += `<text x="0" y="${yy + 13}" class="hl">${esc(name)}</text><rect x="${lw}" y="${yy + 4}" width="${w.toFixed(1)}" height="11" rx="2" style="fill:${it.color || "#7a8699"}"/>` +
        `<text x="${(lw + w + 5).toFixed(1)}" y="${yy + 13}" class="hv">${esc(unit === "d" ? it.value + " d" : fmtH(it.value * 60))}</text>`;
    });
    return h("div", { class: "rp-chart", html: out + "</svg>" });
  },

  burnupSvg(weeks, actualCum, plannedCum, budget, eac) {
    const width = 360, height = 170, pl = 32, pb = 20, pt = 12, pr = 10, n = weeks.length;
    const mx = Math.max(1, budget || 0, eac, ...plannedCum, ...actualCum) * 1.12;
    const x = (i) => pl + (n > 1 ? (i * (width - pl - pr)) / (n - 1) : 0);
    const y = (v) => pt + (height - pb - pt) - (v / mx) * (height - pb - pt);
    const step = mx > 400 ? 100 : mx > 160 ? 50 : mx > 60 ? 25 : 10;
    let out = `<svg viewBox="0 0 ${width} ${height}" width="100%" role="img">`;
    for (let v = 0; v <= mx; v += step) out += `<line x1="${pl}" x2="${width - pr}" y1="${y(v).toFixed(1)}" y2="${y(v).toFixed(1)}" class="g"/><text x="${pl - 5}" y="${(y(v) + 3).toFixed(1)}" class="ax" text-anchor="end">${v}</text>`;
    const every = Math.ceil(n / 9);
    weeks.forEach((w, i) => { if (i % every === 0 || i === n - 1) out += `<text x="${x(i).toFixed(1)}" y="${height - 5}" class="ax" text-anchor="middle">${esc(w)}</text>`; });
    if (budget) out += `<line x1="${pl}" x2="${width - pr}" y1="${y(budget).toFixed(1)}" y2="${y(budget).toFixed(1)}" class="budget"/><text x="${pl + 4}" y="${(y(budget) - 4).toFixed(1)}" class="ax red">budget ${esc(fmtH(budget * 60))}</text>`;
    if (plannedCum.some((v) => v > 0)) out += `<polyline points="${plannedCum.map((v, i) => `${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" ")}" class="plan"/>`;
    const k = actualCum.length - 1;
    if (k >= 0) {
      out += `<polyline points="${actualCum.map((v, i) => `${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" ")}" class="act"/>`;
      out += `<line x1="${x(k).toFixed(1)}" y1="${y(actualCum[k]).toFixed(1)}" x2="${x(n - 1).toFixed(1)}" y2="${y(eac).toFixed(1)}" class="fc"/>`;
      out += `<circle cx="${x(k).toFixed(1)}" cy="${y(actualCum[k]).toFixed(1)}" r="3" class="dot-act"/><text x="${(x(k) + 5).toFixed(1)}" y="${(y(actualCum[k]) + 12).toFixed(1)}" class="bt">${esc(fmtH(actualCum[k] * 60))} now</text>`;
    }
    out += `<circle cx="${x(n - 1).toFixed(1)}" cy="${y(eac).toFixed(1)}" r="3" class="dot-fc"/><text x="${(x(n - 1) - 4).toFixed(1)}" y="${(y(eac) - 6).toFixed(1)}" class="bt" text-anchor="end">forecast ${esc(fmtH(eac * 60))}</text>`;
    return h("div", { class: "rp-chart", html: out + "</svg>" });
  },

  /* ======================================================== 1. weekly status update */

  weekly() {
    const st = this.settings();
    const from = this.view.week, to = addDays(from, 6);
    const days = Array.from({ length: 7 }, (_, i) => addDays(from, i));
    const weekendWork = days.slice(5).some((d) => Store.logList().some((l) => l.date === d));
    const shownDays = weekendWork ? days : days.slice(0, 5);
    const logs = Store.logList().filter((l) => l.date >= from && l.date <= to);
    const units = this.units();
    const unitOfCard = new Map();
    for (const u of units) for (const r of u.cards) unitOfCard.set(r.id, u);

    // hours by project × day
    const grid = new Map();
    for (const l of logs) {
      const r = Store.state.resources[l.resourceId];
      const key = Store.projectKey(r);
      const row = grid.get(key) || grid.set(key, {}).get(key);
      row[l.date] = (row[l.date] || 0) + l.minutes;
    }
    const keys = [...grid.keys()].sort((a, b) => (this.isInternal(a) - this.isInternal(b)) || (!a - !b) || this.projLabel(a).localeCompare(this.projLabel(b)));
    const total = logs.reduce((s, l) => s + l.minutes, 0);
    const internal = grid.has(RP_INTERNAL) ? Object.values(grid.get(RP_INTERNAL)).reduce((s, v) => s + v, 0) : 0;
    const projectMin = total - internal;
    const issued = units.filter((u) => u.done && u.doneAt >= from && u.doneAt <= to && !this.isInternal(u.project));
    const waiting = units.filter((u) => u.onHold && !u.archived && !this.isInternal(u.project));
    const weekAsOf = to < todayISO() ? to : todayISO();
    const overdue = units.filter((u) => !u.done && !u.archived && u.dueDate && u.dueDate < weekAsOf && !this.isInternal(u.project));
    const capMin = st.capacity * 60;

    const dayTot = shownDays.map((d) => logs.reduce((s, l) => s + (l.date === d ? l.minutes : 0), 0));
    const hoursTable = this.table(
      ["Project", ...shownDays.map((d) => h("th", { class: "num" }, WEEKDAYS[(fromISO(d).getDay() + 6) % 7] + " " + fromISO(d).getDate())), h("th", { class: "num" }, "Total"), h("th", { class: "num" }, "Share")],
      keys.map((k) => {
        const row = grid.get(k), sum = Object.values(row).reduce((s, v) => s + v, 0);
        return h("tr", { class: this.isInternal(k) ? "intl" : "" },
          h("td", {}, this.chip(this.projColor(k)), this.projLabel(k)),
          shownDays.map((d) => this.num(row[d] ? fmtH(row[d]) : "·")),
          this.num(fmtH(sum), "b"), this.num(total ? Math.round((sum / total) * 100) + "%" : ""));
      }),
      h("tr", {}, h("td", {}, "Day total"), dayTot.map((m) => this.num(fmtH(m))), this.num(fmtH(total)), this.num("100%")));

    // progress per unit worked this week
    const worked = new Map();
    for (const l of logs) {
      const u = unitOfCard.get(l.resourceId);
      if (!u || this.isInternal(u.project)) continue;
      worked.set(u, (worked.get(u) || 0) + l.minutes);
    }
    for (const u of issued) if (!worked.has(u)) worked.set(u, 0);
    const prog = [...worked.entries()].sort((a, b) => this.projLabel(a[0].project).localeCompare(this.projLabel(b[0].project)) || b[1] - a[1]);
    const progressTable = prog.length ? this.table(["Project", "Deliverable / task", h("th", { class: "num" }, "Week"), "Where it stands"],
      prog.map(([u, m]) => h("tr", {},
        h("td", { class: "nowrap" }, this.chip(this.projColor(u.project)), this.projLabel(u.project)),
        h("td", {}, (u.kind === "deliverable" ? "◆ " : "") + u.title),
        this.num(m ? fmtH(m) : "—"),
        h("td", {}, u.done && u.doneAt >= from && u.doneAt <= to ? this.colPill(u) : (u.statusNote || (u.column ? u.column.label : "")))))) : h("p", { class: "rp-muted" }, "No project work logged this week.");

    const asOf = to < todayISO() ? to : todayISO();
    const waitTable = waiting.length ? this.table(["Item", "Waiting on / status", h("th", { class: "num" }, "Days")],
      waiting.map((u) => {
        const since = this.unitHoldSince(u);
        return h("tr", {},
          h("td", {}, this.dot(this.rag(u, asOf)), h("b", {}, u.title), u.dueDate && u.dueDate < asOf ? h("span", { class: "rp-red small" }, " overdue") : null),
          h("td", {}, u.statusNote || "—"),
          this.num(since ? String(Math.max(0, daysBetween(since, asOf))) : "—"));
      })) : h("p", { class: "rp-muted" }, "Nothing is waiting on others.");

    // plan for next week: remaining estimate spread over each item's planned window
    const nFrom = addDays(from, 7), nTo = addDays(from, 11);
    const plan = [];
    for (const u of units) {
      if (u.done || u.archived || this.isInternal(u.project) || !u.dueDate) continue;
      const start = u.startDate || nFrom;
      // Overdue items carry all their remaining hours into next week.
      if (u.dueDate >= nFrom && start > nTo) continue;
      const remaining = u.estHours ? Math.max(0, u.estHours - this.actual(u) / 60) : null;
      let hrs = null;
      if (remaining != null) {
        const a = start > nFrom ? start : nFrom;
        const windowDays = Math.max(1, this.workdays(a, u.dueDate > a ? u.dueDate : a));
        const inWeek = this.workdays(a, u.dueDate < nTo ? u.dueDate : nTo);
        hrs = u.dueDate < nFrom ? remaining : remaining * Math.min(1, inWeek / windowDays);
      }
      plan.push({ u, hrs });
    }
    plan.sort((a, b) => a.u.dueDate.localeCompare(b.u.dueDate));
    const planned = plan.reduce((s, p) => s + (p.hrs || 0), 0);
    const planTable = plan.length ? this.table(["Deliverable / task", h("th", { class: "num" }, "Plan"), "Due"],
      plan.map(({ u, hrs }) => h("tr", {},
        h("td", {}, this.chip(this.projColor(u.project)), (u.kind === "deliverable" ? "◆ " : "") + u.title),
        this.num(hrs == null ? "—" : fmtH(Math.round(hrs * 2) / 2 * 60)),
        h("td", { class: "nowrap" + (u.dueDate < nFrom ? " rp-red" : "") }, fmtShortDate(u.dueDate)))),
      h("tr", {}, h("td", {}, "Planned"), this.num(fmtH(Math.round(planned * 2) / 2 * 60)), h("td", { class: "rp-muted" }, "of " + st.capacity + "h"))) : h("p", { class: "rp-muted" }, "Nothing planned for next week (give tasks planned dates and estimates).");

    // highlights (your words), editable here, printed as text
    const hl = st.highlights[from] || "";
    const area = h("textarea", { class: "rp-hl-input no-print", rows: "3", placeholder: "Highlights for your manager: 2–3 lines in your words (saved with this week)" }, hl);
    const printed = h("div", { class: "rp-hl-print print-only" }, hl);
    area.addEventListener("input", () => { printed.textContent = area.value; });
    area.addEventListener("change", () => Store.commit((s) => { s.settings.weeklyHighlights = Object.assign({}, s.settings.weeklyHighlights, { [from]: area.value.trim() }); }));

    const out = [
      this.header("Weekly status update", `Week ${isoWeek(from)} · ${fmtShortDate(from)} – ${fmtDate(addDays(from, 4))}`, [["For", "Team manager"], ["From", st.author], ["Date", fmtDate(todayISO())]]),
      this.kpis([
        ["Hours vs capacity", `${fmtH(total)} / ${st.capacity}h`, [this.bar((total / capMin) * 100), " " + Math.round((total / capMin) * 100) + "%"]],
        ["Project time", fmtH(projectMin), total ? `${Math.round((projectMin / total) * 100)}% of logged · internal ${fmtH(internal)}` : "—"],
        ["Issued this week", String(issued.length), issued.map((u) => u.title).join(", ") || "—", issued.length ? "good" : ""],
        ["Waiting / overdue", `${waiting.length} / ${overdue.length}`, waiting.length || overdue.length ? "see below" : "none", waiting.length || overdue.length ? "warn" : ""],
      ]),
      h("div", { class: "rp-callout" + (hl ? "" : " empty-hl") }, h("b", {}, "Highlights"), area, printed),
      this.h2("Hours by project"), keys.length ? hoursTable : h("p", { class: "rp-muted" }, "No hours logged this week."),
      this.h2("Progress this week"), progressTable,
      h("div", { class: "rp-two" },
        h("div", {}, this.h2("Waiting on others"), waitTable),
        h("div", {}, this.h2("Plan for next week", fmtShortDate(nFrom) + " – " + fmtShortDate(nTo)), planTable)),
    ];
    if (this.view.notes && logs.length) {
      out.push(this.h2("Appendix · session notes"), this.table(["Date", "Project", "Task", h("th", { class: "num" }, "Hours"), "Note"],
        logs.slice().sort((a, b) => a.date.localeCompare(b.date) || (a.createdAt || "").localeCompare(b.createdAt || "")).map((l) => {
          const r = Store.state.resources[l.resourceId] || {};
          return h("tr", {}, h("td", { class: "nowrap" }, fmtShortDate(l.date)), h("td", {}, this.chip(this.projColor(Store.projectKey(r))), this.projLabel(Store.projectKey(r))),
            h("td", {}, r.title || "(deleted)"), this.num(fmtH(l.minutes)), h("td", { class: "rp-note-cell" }, l.note || ""));
        }), null, "rp-small"));
    }
    out.push(h("p", { class: "rp-fine" }, "Plan = remaining estimate of items whose planned dates fall in next week, spread over their planned working days."));

    // CSV: hours grid + sessions
    const rows = [["Project", "Task", ...shownDays, "Total (h)"]];
    const byTask = new Map();
    for (const l of logs) {
      const r = Store.state.resources[l.resourceId] || {};
      const k = (Store.projectLabel(Store.projectKey(r))) + "\u0000" + (r.title || "(deleted)");
      const row = byTask.get(k) || byTask.set(k, {}).get(k);
      row[l.date] = (row[l.date] || 0) + l.minutes;
    }
    for (const [k, row] of [...byTask.entries()].sort()) {
      const [p, t] = k.split("\u0000");
      rows.push([p, t, ...shownDays.map((d) => hoursNum(row[d] || 0)), hoursNum(Object.values(row).reduce((s, v) => s + v, 0))]);
    }
    rows.push([], ["Date", "Project", "Task", "Hours", "Note"]);
    for (const l of logs.slice().sort((a, b) => a.date.localeCompare(b.date))) {
      const r = Store.state.resources[l.resourceId] || {};
      rows.push([l.date, Store.projectLabel(Store.projectKey(r)), r.title || "", hoursNum(l.minutes), l.note || ""]);
    }
    this.csv = { name: `weekly-status-${from}.csv`, rows };
    return out;
  },

  /* ======================================================== 2. project status */

  project() {
    const key = this.view.project;
    if (!key) return [this.header("Project status", "No projects yet", []), h("p", { class: "rp-muted" }, "Give your tasks a project to use this report.")];
    const st = this.settings();
    const asOf = todayISO();
    const pr = this.projectRag(key, asOf);
    const units = pr.units.filter((u) => !u.archived || u.logs.length);
    const budget = this.budgetFor(key, units);
    const act = units.reduce((s, u) => s + this.actual(u), 0) / 60;
    const est = units.reduce((s, u) => s + (u.estHours || 0), 0);
    const eac = units.reduce((s, u) => s + this.forecast(u), 0);
    const issued = units.filter((u) => u.done);
    const open = units.filter((u) => !u.done);
    const nextDue = open.filter((u) => u.dueDate && u.dueDate >= asOf).sort((a, b) => a.dueDate.localeCompare(b.dueDate))[0];
    const lastWeek = addDays(asOf, -7);
    const sinceWeek = units.reduce((s, u) => s + this.minutesIn(u.logs, addDays(lastWeek, 1), asOf), 0);

    // burn-up per week
    const allLogs = units.flatMap((u) => u.logs);
    const dates = [...allLogs.map((l) => l.date), ...units.map((u) => u.startDate).filter(Boolean)].sort();
    const firstWeek = startOfWeek(dates[0] || asOf);
    const lastDue = units.map((u) => u.dueDate).filter(Boolean).sort().pop() || asOf;
    const endWeek = startOfWeek(lastDue > asOf ? lastDue : asOf);
    const weeks = [];
    for (let w = firstWeek; w <= endWeek && weeks.length < 60; w = addDays(w, 7)) weeks.push(w);
    const nowIdx = weeks.indexOf(startOfWeek(asOf));
    const actualCum = [];
    let cum = 0;
    weeks.forEach((w, i) => { if (i <= nowIdx) { cum += this.minutesIn(allLogs, w, addDays(w, 6)) / 60; actualCum.push(cum); } });
    const plannedCum = weeks.map((w) => units.reduce((s, u) => {
      if (!u.estHours || !u.dueDate) return s;
      const a = u.startDate || u.dueDate, end = addDays(w, 6);
      if (end < a) return s;
      const tot = Math.max(1, this.workdays(a, u.dueDate));
      return s + u.estHours * Math.min(1, this.workdays(a, end < u.dueDate ? end : u.dueDate) / tot);
    }, 0));

    // decisions / inputs needed (generated from waiting, overdue and over-estimate items)
    const asks = [];
    for (const u of open) {
      if (u.onHold) {
        const since = this.unitHoldSince(u);
        asks.push([this.rag(u, asOf), h("span", {}, h("b", {}, u.title), ": waiting" + (u.statusNote ? " · " + u.statusNote : "") + (since ? ` (since ${fmtShortDate(since)}, ${daysBetween(since, asOf)} days)` : ""))]);
      } else if (u.dueDate && u.dueDate < asOf) {
        asks.push(["R", h("span", {}, h("b", {}, u.title), `: past due (${fmtShortDate(u.dueDate)})` + (u.statusNote ? " · " + u.statusNote : ""))]);
      }
      if (u.estHours && this.actual(u) / 60 > u.estHours) {
        asks.push(["A", h("span", {}, h("b", {}, u.title), `: ${fmtH(this.actual(u))} spent vs ${u.estHours}h estimate. Accept the extra, or adjust scope?`)]);
      }
    }

    const dRows = units.slice().sort((a, b) => (a.done - b.done) || (a.dueDate || "9").localeCompare(b.dueDate || "9")).map((u) => {
      const a = this.actual(u) / 60, f = this.forecast(u), over = u.estHours && f > u.estHours + 0.001;
      const lv = this.rag(u, asOf);
      return h("tr", {},
        h("td", {}, this.dot(lv), h("b", {}, (u.kind === "deliverable" ? "◆ " : "") + u.title),
          u.kind === "deliverable" ? h("span", { class: "rp-muted small" }, ` · ${u.cards.length} card${u.cards.length === 1 ? "" : "s"}`) : null,
          h("div", { class: "rp-st" }, u.statusNote || (u.done ? "" : "—"))),
        h("td", {}, this.colPill(u)),
        this.num(`${fmtH(a * 60)} / ${u.estHours ? fmtH(u.estHours * 60) : "—"}`),
        h("td", { class: "pc" }, u.estHours ? [this.bar((a / u.estHours) * 100, a > u.estHours), h("span", { class: "rp-pct" + (a > u.estHours ? " rp-red" : "") }, Math.round((a / u.estHours) * 100) + "%")] : ""),
        this.num(fmtH(f * 60) + (over ? ` (+${fmtH((f - u.estHours) * 60)})` : ""), over ? "rp-red b" : ""),
        h("td", { class: "nowrap" + (lv === "R" && !u.done ? " rp-red b" : "") }, u.dueDate ? fmtShortDate(u.dueDate) : "—"));
    });

    const soon = [];
    for (const u of open) {
      if (u.startDate && u.startDate > asOf && u.startDate <= addDays(asOf, 14)) soon.push([u.startDate, `${u.title} starts`, u.estHours ? fmtH(u.estHours * 60) + " estimate" : ""]);
      if (u.dueDate && u.dueDate >= asOf && u.dueDate <= addDays(asOf, 14)) {
        const left = u.estHours ? Math.max(0, u.estHours - this.actual(u) / 60) : null;
        soon.push([u.dueDate, `${u.title} due`, (left != null ? fmtH(left * 60) + " left · " : "") + ({ G: "on track", A: "at risk", R: "late" }[this.rag(u, asOf)])]);
      }
    }
    soon.sort((a, b) => a[0].localeCompare(b[0]));

    const budgetTxt = budget.hours ? fmtH(budget.hours * 60) : "—";
    const out = [
      this.header("Project status", [this.chip(this.projColor(key)), this.projLabel(key)], [["For", "Project manager"], ["From", st.author], ["As of", fmtDate(asOf)]]),
      h("div", { class: "rp-ragrow" },
        h("span", { class: "rl" }, "Overall"), this.ragChip(pr.overall),
        h("span", { class: "rl" }, "Schedule"), this.ragChip(pr.schedule, { G: "Green", A: "Amber · at risk", R: "Red · overdue" }[pr.schedule]),
        h("span", { class: "rl" }, "Budget"), this.ragChip(pr.budget, budget.hours ? ({ G: "Green", A: "Amber", R: "Red" }[pr.budget] + ` · forecast ${eac >= budget.hours ? "+" : ""}${Math.round(((eac - budget.hours) / budget.hours) * 100)}%`) : "no budget set")),
      this.kpis([
        ["Budget", budgetTxt, budget.source === "set" ? (budget.hours ? `${Math.round((act / budget.hours) * 100)}% spent · ${fmtH(act * 60)}` : "") : "sum of estimates · " + fmtH(act * 60) + " spent"],
        ["Forecast at completion", fmtH(eac * 60), budget.hours ? `${eac >= budget.hours ? "+" : "−"}${fmtH(Math.abs(eac - budget.hours) * 60)} vs budget` : "", budget.hours && eac > budget.hours ? "warn" : ""],
        ["Issued", `${issued.length} / ${units.length}`, nextDue ? `next due: ${nextDue.title} · ${fmtShortDate(nextDue.dueDate)}` : "no upcoming due dates"],
        ["Last 7 days", "+" + fmtH(sinceWeek), `${open.filter((u) => u.onHold).length} waiting · ${open.filter((u) => u.dueDate && u.dueDate < asOf).length} overdue`],
      ]),
      h("div", { class: "rp-two w60" },
        h("div", {}, this.h2("Hours burn-up", "actual vs planned vs budget"),
          this.burnupSvg(weeks.map((w) => "w" + isoWeek(w)), actualCum, plannedCum, budget.hours || 0, eac),
          h("div", { class: "rp-legend" }, h("span", { class: "lk act" }), "actual ", h("span", { class: "lk plan" }), "planned (estimates over planned dates) ", h("span", { class: "lk bud" }), "budget")),
        h("div", {}, this.h2("Decisions / inputs needed"),
          asks.length ? h("ul", { class: "rp-asks" }, asks.map(([lv, txt]) => h("li", {}, this.dot(lv), txt))) : h("p", { class: "rp-muted" }, "Nothing needs the PM's attention."))),
      this.h2("Deliverables"),
      units.length ? this.table(["Deliverable / status", "Column", h("th", { class: "num" }, "Actual / est."), "vs estimate", h("th", { class: "num" }, "Forecast"), "Due"], dRows,
        h("tr", {}, h("td", {}, "Total"), h("td", {}), this.num(`${fmtH(act * 60)} / ${est ? fmtH(est * 60) : "—"}`), h("td", {}), this.num(fmtH(eac * 60)), h("td", {}))) : h("p", { class: "rp-muted" }, "No tasks in this project."),
      this.h2("Next 2 weeks", fmtShortDate(addDays(asOf, 1)) + " – " + fmtShortDate(addDays(asOf, 14))),
      soon.length ? this.table(["Date", "What", "Note"], soon.map(([d, w, n]) => h("tr", {}, h("td", { class: "nowrap" }, fmtShortDate(d)), h("td", {}, w), h("td", { class: n.includes("late") ? "rp-red" : n.includes("risk") ? "rp-amber" : "rp-muted" }, n)))) : h("p", { class: "rp-muted" }, "No starts or due dates in the next two weeks."),
      h("p", { class: "rp-fine" }, "Ratings: red = past due date, or forecast more than 10% over budget; amber = waiting more than 5 days, over its estimate, or forecast over budget; green otherwise. Forecast = actual for issued items, otherwise the larger of estimate and actual."),
    ];
    this.csv = {
      name: `project-status-${this.projLabel(key).replace(/[^\w-]+/g, "_")}-${asOf}.csv`,
      rows: [["Deliverable / task", "Kind", "Column", "Actual (h)", "Estimate (h)", "Forecast (h)", "Due", "Issued", "Rating", "Status"],
        ...units.map((u) => [u.title, u.kind, u.done ? "Issued" : (u.column ? u.column.label : ""), hoursNum(this.actual(u)), u.estHours || "", hoursNum(this.forecast(u) * 60), u.dueDate, u.doneAt, this.rag(u, asOf), u.statusNote])],
    };
    return out;
  },

  /* ======================================================== 3. monthly capacity & delivery */

  monthly() {
    const st = this.settings();
    const [yy, mm] = this.view.month.split("-").map(Number);
    const from = `${yy}-${pad2(mm)}-01`;
    const to = toISO(new Date(yy, mm, 0));
    const asOf = to < todayISO() ? to : todayISO();
    const logs = Store.logList().filter((l) => l.date >= from && l.date <= to);
    const units = this.units();
    const weeks = [];
    for (let w = startOfWeek(from); w <= to; w = addDays(w, 7)) {
      const a = w < from ? from : w, b = addDays(w, 6) > to ? to : addDays(w, 6);
      weeks.push({ a, b, label: `w${isoWeek(w)} · ${fromISO(a).getDate()}–${fromISO(b).getDate()}`, cap: (st.capacity / 5) * this.workdays(a, b) });
    }
    const cap = weeks.reduce((s, w) => s + w.cap, 0);
    const per = new Map();
    for (const l of logs) {
      const key = Store.projectKey(Store.state.resources[l.resourceId]);
      const row = per.get(key) || per.set(key, weeks.map(() => 0)).get(key);
      const i = weeks.findIndex((w) => l.date >= w.a && l.date <= w.b);
      if (i >= 0) row[i] += l.minutes / 60;
    }
    const keys = [...per.keys()].sort((a, b) => (this.isInternal(a) - this.isInternal(b)) || (!a - !b) || this.projLabel(a).localeCompare(this.projLabel(b)));
    const total = logs.reduce((s, l) => s + l.minutes, 0) / 60;
    const internal = per.has(RP_INTERNAL) ? per.get(RP_INTERNAL).reduce((s, v) => s + v, 0) : 0;
    const issued = units.filter((u) => u.done && u.doneAt >= from && u.doneAt <= to && !this.isInternal(u.project));
    const acc = issued.filter((u) => u.estHours);
    const accEst = acc.reduce((s, u) => s + u.estHours, 0), accAct = acc.reduce((s, u) => s + this.actual(u) / 60, 0);

    const waitItems = units.map((u) => ({ u, days: u.cards.reduce((s, r) => s + this.holdDaysIn(r, from, to), 0) })).filter((x) => x.days > 0).sort((a, b) => b.days - a.days).slice(0, 7);
    const byCat = new Map();
    for (const l of logs) {
      const r = Store.state.resources[l.resourceId] || {};
      const c = Store.category(r.categoryId);
      const k = c ? c.id : "";
      byCat.set(k, (byCat.get(k) || 0) + l.minutes / 60);
    }
    const intl = new Map();
    for (const l of logs) {
      const r = Store.state.resources[l.resourceId] || {};
      if (!this.isInternal(Store.projectKey(r))) continue;
      intl.set(r.title, (intl.get(r.title) || 0) + l.minutes / 60);
    }
    const nm = toISO(new Date(yy, mm, 1)), nmEnd = toISO(new Date(yy, mm + 1, 0));
    const deadlines = units.filter((u) => !u.done && !u.archived && u.dueDate >= nm && u.dueDate <= nmEnd).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
    const monthName = fromISO(from).toLocaleString("en-GB", { month: "long", year: "numeric" });

    const out = [
      this.header("Monthly capacity & delivery", monthName, [["For", "Team manager"], ["From", st.author], ["Working days", String(this.workdays(from, to))], ["Capacity", fmtH(cap * 60)]]),
      this.kpis([
        ["Utilization", cap ? Math.round((total / cap) * 100) + "%" : "—", `${fmtH(total * 60)} logged of ${fmtH(cap * 60)}`],
        ["Project time", total ? Math.round(((total - internal) / total) * 100) + "%" : "—", `${fmtH((total - internal) * 60)} · internal ${fmtH(internal * 60)}`],
        ["Issued", String(issued.length), issued.map((u) => u.title).slice(0, 4).join(", ") || "—"],
        ["Estimate accuracy", acc.length ? (accAct >= accEst ? "+" : "") + Math.round(((accAct - accEst) / accEst) * 100) + "%" : "—", acc.length ? `on ${acc.length} issued with an estimate` : "no issued items with estimates", acc.length ? (accAct > accEst * 1.1 ? "warn" : "good") : ""],
      ]),
      this.h2("Weekly load vs capacity", "bars = hours by project · dashed = capacity"),
      this.barsSvg(weeks.map((w) => w.label), keys.map((k) => ({ label: this.projLabel(k), color: this.projColor(k), values: per.get(k) })), weeks.map((w) => w.cap), 690, 185),
      h("div", { class: "rp-legend" }, keys.map((k) => [this.chip(this.projColor(k)), this.projLabel(k) + "  "])),
      keys.length ? this.table(["Project", ...weeks.map((w) => h("th", { class: "num" }, w.label.split(" · ")[0])), h("th", { class: "num" }, "Total"), h("th", { class: "num" }, "Share"), "Rating"],
        keys.map((k) => {
          const v = per.get(k), sum = v.reduce((s, x) => s + x, 0);
          return h("tr", { class: this.isInternal(k) ? "intl" : "" }, h("td", {}, this.chip(this.projColor(k)), this.projLabel(k)),
            v.map((x) => this.num(x ? fmtH(x * 60) : "·")), this.num(fmtH(sum * 60), "b"), this.num(total ? Math.round((sum / total) * 100) + "%" : ""),
            h("td", {}, this.isInternal(k) || !k ? "—" : this.ragChip(this.projectRag(k, asOf).overall)));
        }),
        h("tr", {}, h("td", {}, "Total"), weeks.map((w, i) => this.num(fmtH(keys.reduce((s, k) => s + per.get(k)[i], 0) * 60))), this.num(fmtH(total * 60)), this.num("100%"), h("td", {}))) : h("p", { class: "rp-muted" }, "No hours logged this month."),
      h("div", { class: "rp-two" },
        h("div", {}, this.h2("Estimate accuracy", "issued this month"),
          acc.length ? this.table(["Deliverable / task", h("th", { class: "num" }, "Est."), h("th", { class: "num" }, "Actual"), h("th", { class: "num" }, "Diff")],
            acc.map((u) => {
              const a = this.actual(u) / 60, d = Math.round(((a - u.estHours) / u.estHours) * 100);
              return h("tr", {}, h("td", {}, this.chip(this.projColor(u.project)), u.title), this.num(fmtH(u.estHours * 60)), this.num(fmtH(a * 60)), this.num((d >= 0 ? "+" : "") + d + "%", d > 0 ? "rp-red" : "rp-green"));
            }), h("tr", {}, h("td", {}, "Total"), this.num(fmtH(accEst * 60)), this.num(fmtH(accAct * 60)), this.num((accAct >= accEst ? "+" : "") + Math.round(((accAct - accEst) / accEst) * 100) + "%"))) : h("p", { class: "rp-muted" }, "Nothing with an estimate was issued this month."),
          this.h2("By category"),
          this.hbarsSvg([...byCat.entries()].sort((a, b) => b[1] - a[1]).map(([k, v]) => ({ label: (Store.category(k) || {}).name || "Uncategorised", value: v, color: Store.categoryColor(k || null) })))),
        h("div", {}, this.h2("Time lost waiting", "days in waiting columns"),
          waitItems.length ? this.hbarsSvg(waitItems.map((x) => ({ label: x.u.title, value: x.days, color: "#d48a00" })), "d") : h("p", { class: "rp-muted" }, "No waiting time recorded this month."),
          this.h2("Internal time"),
          this.hbarsSvg([...intl.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([k, v]) => ({ label: k, value: v, color: "#9aa1ad" }))))),
      this.h2("Deadlines next month", fromISO(nm).toLocaleString("en-GB", { month: "long" })),
      deadlines.length ? this.table(["Due", "Deliverable / task", "Rating"], deadlines.map((u) => h("tr", {},
        h("td", { class: "nowrap" }, fmtShortDate(u.dueDate)), h("td", {}, this.chip(this.projColor(u.project)), u.title),
        h("td", {}, this.ragChip(this.rag(u, asOf), { G: "on track", A: "at risk", R: "late" }[this.rag(u, asOf)]))))) : h("p", { class: "rp-muted" }, "No due dates next month."),
    ];
    this.csv = {
      name: `monthly-capacity-${this.view.month}.csv`,
      rows: [["Project", ...weeks.map((w) => w.label), "Total (h)"],
        ...keys.map((k) => [this.projLabel(k), ...per.get(k).map((x) => hoursNum(x * 60)), hoursNum(per.get(k).reduce((s, x) => s + x, 0) * 60)]),
        ["Capacity", ...weeks.map((w) => w.cap), cap]],
    };
    return out;
  },

  /* ======================================================== 4. task / deliverable history */

  history() {
    const v = this.view.item || "";
    const [kind, id] = v.split(":");
    const u = kind === "d" && Store.deliverable(id) ? this.dlvUnit(Store.deliverable(id)) : kind === "c" && Store.state.resources[id] ? this.cardUnit(Store.state.resources[id]) : null;
    if (!u) return [this.header("Task history", "Nothing selected", []), h("p", { class: "rp-muted" }, "Pick a task or deliverable above.")];
    const asOf = todayISO();
    const a = this.actual(u) / 60, f = this.forecast(u);
    const focus = u.logs.filter((l) => l.focus);
    const lv = this.rag(u, asOf);
    const cat = Store.category(u.categoryId);

    // time per column (cards only), from the hidden move records
    let seg = null;
    if (u.kind === "card") {
      const r = u.cards[0];
      const moves = (r.history || []).filter((e) => e.kind === "move").sort((x, y) => (x.at || x.date).localeCompare(y.at || y.date));
      const start = [r.createdAt, (u.logs[0] || {}).date, (moves[0] || {}).date].filter(Boolean).sort()[0] || asOf;
      const end = u.done && u.doneAt ? u.doneAt : asOf;
      const spans = new Map();
      let curLabel = moves.length ? moves[0].from : Store.column(r.status).label, curStart = start;
      for (const m of moves) {
        spans.set(curLabel, (spans.get(curLabel) || 0) + Math.max(0, daysBetween(curStart, m.date)));
        curLabel = m.to; curStart = m.date;
      }
      if (!u.done) spans.set(curLabel, (spans.get(curLabel) || 0) + Math.max(0, daysBetween(curStart, end)));
      const colColor = (label) => { const c = Store.columns().find((x) => x.label === label); return c ? ({ todo: "#b9bec8", doing: "#2f6fdb", hold: "#d48a00", done: "#1f9d74" }[c.kind]) : "#b9bec8"; };
      const parts = [...spans.entries()].filter(([, d]) => d > 0);
      const tot = parts.reduce((s, [, d]) => s + d, 0);
      if (tot) seg = [h("div", { class: "rp-seg" }, parts.map(([l, d]) => h("span", { style: { flex: String(d), background: colColor(l) }, title: `${l} · ${d} d` }))),
        h("div", { class: "rp-legend" }, parts.map(([l, d]) => [h("span", { class: "lk", style: { background: colColor(l) } }), `${l} ${d}d   `]))];
    }

    // work log: sessions + status updates ("moved" entries are left out)
    const entries = [];
    for (const l of u.logs) entries.push({ date: l.date, at: l.createdAt || "", log: l });
    for (const r of u.cards) for (const e of (r.history || [])) if (e.kind === "status" || e.kind === "sessions") entries.push({ date: e.date, at: e.at || "", event: e, card: r });
    entries.sort((x, y) => y.date.localeCompare(x.date) || y.at.localeCompare(x.at));
    const log = [];
    let last = null;
    for (const en of entries) {
      if (en.date !== last) {
        last = en.date;
        const dm = u.logs.reduce((s, l) => s + (l.date === en.date ? l.minutes : 0), 0);
        log.push(h("div", { class: "rp-tld" }, h("span", {}, fmtDate(en.date)), h("span", {}, dm ? fmtH(dm) : "")));
      }
      if (en.log) {
        const r = Store.state.resources[en.log.resourceId] || {};
        log.push(h("div", { class: "rp-tlr" }, h("span", { class: "rp-tlh" }, fmtH(en.log.minutes)),
          en.log.focus ? h("span", { class: "rp-fo" }, "focus " + en.log.focus) : null,
          u.kind === "deliverable" ? h("span", { class: "rp-card" }, r.title) : null,
          h("span", {}, en.log.note || "")));
      } else if (en.event.kind === "status") {
        log.push(h("div", { class: "rp-tlr st" }, h("span", { class: "rp-kw" }, "status"), h("span", {}, en.event.text ? `“${en.event.text}”` : "cleared")));
      } else {
        log.push(h("div", { class: "rp-tlr st" }, h("span", { class: "rp-kw" }, "0h"), h("span", {}, `${en.event.count} session(s), no time logged` + (en.event.text ? " · " + en.event.text : ""))));
      }
    }

    const out = [
      this.header(u.kind === "deliverable" ? "Deliverable history" : "Task history", [this.chip(this.projColor(u.project)), (u.kind === "deliverable" ? "◆ " : "") + u.title],
        [["Project", this.projLabel(u.project)], ["Category", cat ? cat.name : ""], ["Column", u.done ? "Issued" : (u.column ? u.column.label : "")]]),
      this.kpis([
        ["Hours", fmtH(a * 60), u.estHours ? "of " + fmtH(u.estHours * 60) + " estimate" : "no estimate"],
        ["Progress", u.estHours ? Math.round((a / u.estHours) * 100) + "%" : "—", u.estHours ? this.bar((a / u.estHours) * 100, a > u.estHours) : ""],
        ["Sessions", String(u.sessions), focus.length ? "avg focus " + (focus.reduce((s, l) => s + l.focus, 0) / focus.length).toFixed(1) : ""],
        [u.done ? "Issued" : "Due", u.done ? (u.doneAt ? fmtDate(u.doneAt) : "yes") : (u.dueDate ? fmtDate(u.dueDate) : "—"),
          u.done ? "" : (u.startDate ? "planned from " + fmtShortDate(u.startDate) + " · " : "") + { G: "on track", A: "at risk", R: "late" }[lv], u.done ? "good" : lv === "R" ? "bad" : lv === "A" ? "warn" : ""],
      ]),
      u.statusNote ? h("div", { class: "rp-callout" }, h("b", {}, "Status"), u.statusNote, u.statusUpdatedAt ? h("span", { class: "rp-muted" }, " · updated " + fmtDate(u.statusUpdatedAt)) : null) : null,
    ];
    if (u.kind === "deliverable") {
      out.push(this.h2("Cards"), this.table(["Card", "Column", h("th", { class: "num" }, "Hours"), h("th", { class: "num" }, "Estimate")],
        u.cards.map((r) => h("tr", {}, h("td", {}, r.title), h("td", {}, Store.isDone(r) ? "Done" : Store.column(r.status).label + (r.archived ? " · archived" : "")),
          this.num(fmtH(Store.minutesFor(r.id))), this.num(r.estHours ? fmtH(r.estHours * 60) : "—")))));
    } else if (seg) {
      out.push(this.h2("Time per column", "days in each column"), ...seg);
    }
    out.push(this.h2("Work log", "sessions and status updates"), log.length ? h("div", { class: "rp-tl" }, log) : h("p", { class: "rp-muted" }, "No sessions yet."));
    if (u.notes) out.push(this.h2("Notes"), h("p", { class: "rp-notes" }, u.notes));
    this.csv = {
      name: `history-${u.title.replace(/[^\w-]+/g, "_")}.csv`,
      rows: [["Date", "Card", "Hours", "Focus", "Note"], ...u.logs.map((l) => [l.date, (Store.state.resources[l.resourceId] || {}).title || "", hoursNum(l.minutes), l.focus || "", l.note || ""])],
    };
    return out;
  },
};

/* ---------- helpers ---------- */

// Hours as decimals, e.g. 2.75h (reports read like a timesheet).
function fmtH(min) {
  const v = Math.round(((min || 0) / 60) * 100) / 100;
  return (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0$/, "")) + "h";
}
function hoursNum(min) { return Math.round(((min || 0) / 60) * 100) / 100; }
function csvCell(v) {
  const s = v == null ? "" : String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function isoWeek(iso) {
  const d = fromISO(iso);
  const t = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const day = t.getUTCDay() || 7;
  t.setUTCDate(t.getUTCDate() + 4 - day);
  const y0 = new Date(Date.UTC(t.getUTCFullYear(), 0, 1));
  return Math.ceil(((t - y0) / 86400000 + 1) / 7);
}
